spring:
  server:
    port: 8080

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/onerm
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao: # ??? ???? ?? ??
#            client-id: your_kakao_client_id
#            client-secret: your_kakao_client_secret
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            scope: profile,account_email # ??? ??? ??

# task:
#    scheduling:
#      cron: 0 59 23 * * ? # ???? ??? ??